[build]
  publish = "."

[[headers]]
  for = "/lab01/vinko-assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/assets/*"
  [headers.values]
    Cache-Control = "public, max-age=31536000, immutable"

[[headers]]
  for = "/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"

[[headers]]
  for = "/lab01/*.html"
  [headers.values]
    Cache-Control = "public, max-age=0, must-revalidate"
